/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaRecambios.ventanas;

import buscaRecambios.Listas.Marcas;
import buscaRecambios.Listas.Modelos;
import buscaRecambios.Listas.Piezas;
import buscaRecambios.Renders.AñoMODELORenderer;
import buscaRecambios.Renders.CcMODELORenderer;
import buscaRecambios.Renders.CombustibleMODELORenderer;
import buscaRecambios.Renders.CvMODELORenderer;
import buscaRecambios.Renders.DescPIEZA_Renderer;
import buscaRecambios.Renders.IdMARCA_Renderer;
import buscaRecambios.Renders.IdMODELORenderer;
import buscaRecambios.Renders.IdPIEZA_Renderer;
import buscaRecambios.Renders.MarcaMARCA_Renderer;
import buscaRecambios.Renders.MarcaMODELORenderer;
import buscaRecambios.Renders.ModeloMODELORenderer;
import buscaRecambios.Renders.ModeloPIEZA_Renderer;
import buscaRecambios.Renders.TPiezaPIEZA_Renderer;
import buscaRecambios.Renders.nombrePIEZA_Renderer;
import buscaRecambios.TableModels.TableModelMarcas;
import buscaRecambios.TableModels.TableModelModelos;
import buscaRecambios.TableModels.TableModelPiezas;
import buscaRecambios.entity.Marca;
import buscaRecambios.entity.Modelo;
import buscaRecambios.entity.Pieza;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MostradorPiezas extends javax.swing.JDialog {

    private static Modelo idModelo;
    private static Piezas listapiezas;

    private Marcas listamarcas;
    private Modelos listamodelos;
    EntityManager e = CarPartsWindow.entityManager;

    Query query1;
    Query query2;
    Query query3;
    Query query4;

    TableModelMarcas tablemarca;
    TableModelModelos tablemodelos;
    TableModelPiezas tablemodel;

    /**
     * Creates new form MostradorPiezas
     */
    public MostradorPiezas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        query1 = e.createQuery("SELECT p FROM Pieza p WHERE p.idModelo = :id").setParameter(
                "id", MostradorPiezas.idModelo);
        listapiezas = new Piezas(query1.getResultList());
        tablemodel = new TableModelPiezas(listapiezas);
        jTable1.setModel(tablemodel);

        jTable1.getColumnModel().getColumn(0).setCellRenderer(new IdPIEZA_Renderer());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new ModeloPIEZA_Renderer());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new nombrePIEZA_Renderer());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new TPiezaPIEZA_Renderer());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new DescPIEZA_Renderer());

        query2 = e.createNamedQuery("Marca.findAll");
        listamarcas = new Marcas(query2.getResultList());

        tablemarca = new TableModelMarcas(listamarcas);
        jTable2.setModel(tablemarca);

        jTable2.getColumnModel().getColumn(0).setCellRenderer(new IdMARCA_Renderer());
        jTable2.getColumnModel().getColumn(1).setCellRenderer(new MarcaMARCA_Renderer());

        query3 = e.createNamedQuery("Modelo.findAll");
        listamodelos = new Modelos(query3.getResultList());

        tablemodelos = new TableModelModelos(listamodelos);
        jTable3.setModel(tablemodelos);

        jTable3.getColumnModel().getColumn(0).setCellRenderer(new IdMODELORenderer());
        jTable3.getColumnModel().getColumn(1).setCellRenderer(new MarcaMODELORenderer());
        jTable3.getColumnModel().getColumn(2).setCellRenderer(new ModeloMODELORenderer());
        jTable3.getColumnModel().getColumn(3).setCellRenderer(new CcMODELORenderer());
        jTable3.getColumnModel().getColumn(4).setCellRenderer(new CvMODELORenderer());
        jTable3.getColumnModel().getColumn(5).setCellRenderer(new AñoMODELORenderer());
        jTable3.getColumnModel().getColumn(6).setCellRenderer(new CombustibleMODELORenderer());

    }

    public static void setModelo(Modelo idModelo) {
        MostradorPiezas.idModelo = idModelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SaveChangesPieza = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ShowAllPieza = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SaveChangesMarca = new javax.swing.JButton();
        DeleteMarca = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        SaveChangesModelo = new javax.swing.JButton();
        DeleteModelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        SaveChangesPieza.setText("Guardar Cambios");
        SaveChangesPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesPiezaActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ShowAllPieza.setText("Mostrar Todo");
        ShowAllPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllPiezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowAllPieza)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SaveChangesPieza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowAllPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveChangesPieza)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ListaPiezas", jPanel3);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        SaveChangesMarca.setText("Guardar Cambios");
        SaveChangesMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesMarcaActionPerformed(evt);
            }
        });

        DeleteMarca.setText("Eliminar marca");
        DeleteMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveChangesMarca)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(DeleteMarca)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveChangesMarca)
                    .addComponent(DeleteMarca))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado Marcas", jPanel1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        SaveChangesModelo.setText("Guardar Cambios");
        SaveChangesModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesModeloActionPerformed(evt);
            }
        });

        DeleteModelo.setText("Eliminar Modelo");
        DeleteModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaveChangesModelo)
                        .addGap(18, 298, Short.MAX_VALUE)
                        .addComponent(DeleteModelo))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveChangesModelo)
                    .addComponent(DeleteModelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado Modelos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);

    }//GEN-LAST:event_formWindowClosing

    private void SaveChangesMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesMarcaActionPerformed

        int decision = JOptionPane.showConfirmDialog(this, "Estas seguro que quieres guardar los cambios", 
                "Un momento...", JOptionPane.YES_NO_OPTION);
        if (!e.getTransaction().isActive()) {
            e.getTransaction().begin();
        }
        
        if (decision == JOptionPane.YES_OPTION) {
            e.getTransaction().commit();
            tablemarca.refreshRow(jTable2.getSelectedRow());
        } else {
            if (decision == JOptionPane.NO_OPTION) {
                e.getTransaction().rollback();
                
            }
        }

    }//GEN-LAST:event_SaveChangesMarcaActionPerformed

    private void DeleteMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMarcaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "¿Estás seguro? Se eliminarán los modelos \ny piezas correspondientes",
                "Eliminar marca: " + listamarcas.getMarcaByIndex(jTable2.getSelectedRow()).getMarca(),
                JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            if (!e.getTransaction().isActive()) {
                e.getTransaction().begin();
            }
            Marca marca = listamarcas.getMarcaByIndex(jTable2.getSelectedRow());
            e.remove(marca);
            e.getTransaction().commit();
            tablemodelos.fireTableRowsDeleted(jTable2.getSelectedRow(), jTable2.getSelectedRow());
            tablemarca.fireTableRowsDeleted(jTable2.getSelectedRow(), jTable2.getSelectedRow());
        } else {
            if (result == JOptionPane.CANCEL_OPTION) {
                if (e.getTransaction().isActive()) {
                    e.getTransaction().rollback();
                }
            }
        }


    }//GEN-LAST:event_DeleteMarcaActionPerformed

    private void SaveChangesModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesModeloActionPerformed
        int decision = JOptionPane.showConfirmDialog(this, "Estas seguro que quieres guardar los cambios", 
                "Un momento...", JOptionPane.YES_NO_OPTION);
        if (!e.getTransaction().isActive()) {
            e.getTransaction().begin();
        }
        
        if (decision == JOptionPane.YES_OPTION) {
            e.getTransaction().commit();
            tablemodelos.refreshRow(jTable3.getSelectedRow());
        } else {
            if (decision == JOptionPane.NO_OPTION) {
                if(e.getTransaction().isActive()){
                    e.getTransaction().rollback();
                } 
            }
        }
    }//GEN-LAST:event_SaveChangesModeloActionPerformed

    private void ShowAllPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllPiezaActionPerformed
        //Muestra todas las piezas
        query4 = e.createNamedQuery("Pieza.findAll");
        listapiezas = new Piezas(query4.getResultList());
        TableModelPiezas tablepiezas2 = new TableModelPiezas(listapiezas);
        jTable1.setModel(tablepiezas2);
        
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new IdPIEZA_Renderer());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new ModeloPIEZA_Renderer());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new nombrePIEZA_Renderer());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new TPiezaPIEZA_Renderer());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new DescPIEZA_Renderer());
        
        
    }//GEN-LAST:event_ShowAllPiezaActionPerformed

    private void DeleteModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteModeloActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "¿Estás seguro?",
                "Eliminar marca: " + listamodelos.getModeloByIndex(jTable3.getSelectedRow()).getModelo(),
                JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            if (!e.getTransaction().isActive()) {
                e.getTransaction().begin();
            }
            Modelo modelo = listamodelos.getModeloByIndex(jTable3.getSelectedRow());
            e.remove(modelo);
            e.getTransaction().commit();
            tablemodelos.fireTableRowsDeleted(jTable3.getSelectedRow(), jTable3.getSelectedRow());
        } else {
            if (result == JOptionPane.CANCEL_OPTION) {
                if (e.getTransaction().isActive()) {
                    e.getTransaction().rollback();
                }
            }
        }
    }//GEN-LAST:event_DeleteModeloActionPerformed

    private void SaveChangesPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesPiezaActionPerformed
        int decision = JOptionPane.showConfirmDialog(this, "Estas seguro que quieres guardar los cambios", 
                "Un momento...", JOptionPane.YES_NO_OPTION);
        if (!e.getTransaction().isActive()) {
            e.getTransaction().begin();
        }
        
        if (decision == JOptionPane.YES_OPTION) {
            e.getTransaction().commit();
            tablemodel.refreshRow(jTable1.getSelectedRow());
        } else {
            if (decision == JOptionPane.NO_OPTION) {
                if(e.getTransaction().isActive()){
                    e.getTransaction().rollback();
                } 
            }
        }
    }//GEN-LAST:event_SaveChangesPiezaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "¿Estás seguro?",
                "Eliminar marca: " + listapiezas.getListaPieza().get(jTable1.getSelectedRow()).getNombre(),
                JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            if (!e.getTransaction().isActive()) {
                e.getTransaction().begin();
            }
            Pieza pieza = listapiezas.getListaPieza().get(jTable1.getSelectedRow());
            e.remove(pieza);
            e.getTransaction().commit();
            tablemodelos.fireTableRowsDeleted(jTable1.getSelectedRow(), jTable1.getSelectedRow());
        } else {
            if (result == JOptionPane.CANCEL_OPTION) {
                if (e.getTransaction().isActive()) {
                    e.getTransaction().rollback();
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostradorPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostradorPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostradorPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostradorPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostradorPiezas dialog = new MostradorPiezas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteMarca;
    private javax.swing.JButton DeleteModelo;
    private javax.swing.JButton SaveChangesMarca;
    private javax.swing.JButton SaveChangesModelo;
    private javax.swing.JButton SaveChangesPieza;
    private javax.swing.JButton ShowAllPieza;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
