/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaRecambios.ventanas;

import buscaRecambios.Listas.Marcas;
import buscaRecambios.Listas.Modelos;
import buscaRecambios.MaxLengthDocument;
import buscaRecambios.Renders.AñoMODELORenderer;
import buscaRecambios.Renders.CcMODELORenderer;
import buscaRecambios.Renders.CombustibleMODELORenderer;
import buscaRecambios.Renders.CvMODELORenderer;
import buscaRecambios.Renders.IdMODELORenderer;
import buscaRecambios.Renders.MarcaMODELORenderer;
import buscaRecambios.Renders.ModeloMODELORenderer;
import buscaRecambios.TableModels.TableModelModelos;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Usuario
 */
public class ventanaEjemplo extends javax.swing.JFrame {
    
    Modelos listamodelos;
    Marcas listamarca = new Marcas();
    /**
     * Creates new form ventanaEjemplo
     */
    public ventanaEjemplo() {
        initComponents();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTable1.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
                    public void valueChanged(ListSelectionEvent event) {
                        mostrardetalles();
                    }
                }
            );
        
        jTextField1.setDocument(new MaxLengthDocument());
    }
    
    
    public void mostrardetalles() {
        int indexSelectedRow = jTable1.getSelectedRow();
        if (indexSelectedRow < 0) {
            jTextArea1.setText("Sin selección");
        } else {
            
            jTextArea1.setText("Id: " + String.valueOf(listamodelos.getListamodelos().get(indexSelectedRow).getIdModelo())
           + "\nMarca: " + listamodelos.getModeloByIndex(indexSelectedRow).getIdMarca().getMarca() + "\nModelo: " +
                    listamodelos.getModeloByIndex(indexSelectedRow).getModelo() + "\nCilindrada: " + 
                    listamodelos.getModeloByIndex(indexSelectedRow).getCilindrada() + "\nCv: " + 
                    listamodelos.getModeloByIndex(indexSelectedRow).getCv());
        }
    }
    
    public Marcas getListaMarca() {
        return listamarca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Marca marca;
//        marca = new Marca(1, "Volkswagen");
//        
//        listamarca.addMarca(marca);
//
//        marca = new Marca(2, "Renault");
//        listamarca.addMarca(marca);
//
//        marca = new Marca(3, "Peugeot");
//        listamarca.addMarca(marca);
//
//        Modelo modelo;
//        modelo = new Modelo(1, listamarca.getMarcaByIndex(0), "Golf IV TDI", 1900, 90, 1999, false);
//        listamodelos = new ListaModelos();
//        listamodelos.addModelo(modelo);
//        modelo = new Modelo(2, listamarca.getMarcaByIndex(1), "Megane", 1400, 15, 2013, true);
//        listamodelos.addModelo(modelo);
//
//        TipoPieza tpieza;
//        tpieza = new TipoPieza(1, "Filtros");
//        ListaTipoPiezas listatpiezas = new ListaTipoPiezas();
//        listatpiezas.addTipoPieza(tpieza);
//
//        Pieza pieza;
//        pieza = new Pieza(listamodelos.getModeloByIndex(0), 1,
//                listatpiezas.getTPiezaByIndex(0), "Filtro Aire", null);
//        ListaPiezas listapiezas = new ListaPiezas();
//        listapiezas.addPieza(pieza);
//
//        for (Marca m : listamarca.getListaMarcas()) {
//            System.out.println(m.getMarca());
//        }
//
//        for (Modelo mod : listamodelos.getListamodelos()) {
//            System.out.println(mod.toString());
//        }
//        TableModelMarcas marcastable = new TableModelMarcas(listamarca);
//        jTable1.setModel(marcastable);

        TableModelModelos modelostable = new TableModelModelos(listamodelos);
        jTable1.setModel(modelostable);

        jTable1.getColumnModel().getColumn(0).setCellRenderer(new IdMODELORenderer());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new MarcaMODELORenderer());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new ModeloMODELORenderer());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new CcMODELORenderer());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new CvMODELORenderer());
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new AñoMODELORenderer());
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new CombustibleMODELORenderer());

//          TableModelPiezas piezastable = new TableModelPiezas(listapiezas);
//          jTable1.setModel(piezastable);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaEjemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
